runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

#[START env]
env_variables:
    # Replace user, password, database, project, and instance with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://betest:betesting@/betest?unix_socket=/cloudsql/oshark-148001:us-central1:oshark-be'
#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: oshark-148001:us-central1:oshark-be 
#[END cloudsql_settings]

